language: minimal

os:
  - linux

jobs:
  include:
    - stage: test and build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t howtocards-frontend .
        - docker tag howtocards-frontend howtocards/frontend:$TRAVIS_COMMIT
        - docker images
        - docker push howtocards/frontend:$TRAVIS_COMMIT
