name: Docker Image CI

on:
  push:
    branches:
      - master
      - dev

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.8
        with:
          name: howtocards/frontend/frontend
          username: sergeysova
          password: ${{ secrets.GITHUB_TOKEN }}
          snapshot: true
          tagging: ${{contains(github.ref, 'refs/tags/v')}}
          registry: docker.pkg.github.com
      - name: Trigger Deploy Dev
        run: |
          curl -XPOST -u "sergeysova:${{secrets.GITHUB_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/howtocards/releases/dispatches --data '{"event_type": "build_application"}'
